name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - run: |
          cd docs/.vitepress/dist &&
          git init &&
          git add -A &&
          git commit -m '发布`date`' &&
          git push -f git@github.com:yellowrush888/jbook.git master:gh-pages